name: Game

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wild-thyme
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: rustup target add wasm32-unknown-unknown && cargo build --release --target=wasm32-unknown-unknown
    - name: Run tests
      run: cargo test --verbose
